### ISSUE TITLE
Remove support for pointer-members!

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#103]
Members with the type "some_type*" has been supported by dl since day one but during all these years I have never had a case where I wanted/needed to use it.
IMHO all such cases could just as well be handled by an array + indices userside.
The motivation to remove them then would be that it removes quite a bit of code and complexity.

This issue is mostly here as a "think about this"/"gather input".

**Comment by lundmark** [comment]
Nooooo! We use pointer types! We use it regularly.
