### ISSUE TITLE
DL fails to pack/load specific file

### ISSUE THREAD

**Issue by joeldevahl** [wc-duck/datalibrary#11]
I have the following type library and data file

https://gist.github.com/joeldevahl/91a6c4a3568531cc3053

and doing a dl_pack on cube.mesh with the compiled type library gives me a crash in dl_internal_store_string in the strlen.

datalibrary is at commit a59f48e98dcb5a8174b5587bedfa08cf2e7ee47f

**Comment by wc-duck** [comment]
I'll look at that tonight...

**Comment by wc-duck** [comment]
do you have multiple type-libs loaded in the same context when this error occurs? It seems that there is problems with that from my small tests here at home.

**Comment by joeldevahl** [comment]
In the code I have multiple loaded. However I get a crash running dl_pack with only one typelib too.

**Comment by wc-duck** [comment]
Fixed
