### ISSUE TITLE
datalibrary allocates crazy amounts of memory when loading many type libraries

### ISSUE THREAD

**Issue by lazy909** [wc-duck/datalibrary#110]
The combination of

dl_context_load_type_library
`dl_ctx->member_descs     = dl_grow_array( &dl_ctx->alloc, dl_ctx->member_descs,     &dl_ctx->member_capacity,      dl_ctx->member_count + header.member_count `);`
`
and dl_grow_array
`size_t new_cap = ( ( old_cap < min_inc ) ? old_cap + min_inc : old_cap ) * 2;`

means the library always doubles the amount of memory allocated for each library loaded.

For my libraires it allocated
1. 30 capacity  for a total of 15 members (0 + 15) * 2
2. 60 capacity for a total of 25 members (30) * 2
3. 120 capacity for a total of 33 members (60) * 2
etc...

After loading 18 type libraries with a total of ~120 members, dl_grow_array tried to realloc 250mb of memory

I suggest
size_t new_cap = old_cap < min_inc ? min_inc * 2 : old_cap;

**Comment by wc-duck** [comment]
Ouch! That is definitely not correct. I'll hopefully have some time to fix
that tonight!

**Comment by wc-duck** [comment]
Issue should be solved now.
I removed the use of dl_grow_array and just realloc:ed it thus always keeping it at min-size allocation.

**Comment by wc-duck** [comment]
Oh! And thanks for the bug-report! Its appreciated!

**Comment by lazy909** [comment]
np. It's a nice library :)
/Andrés Hansson
