### ISSUE TITLE
readme I horribly out of date!

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#12]

**Comment by lundmark** [comment]
Do you want help with updating it?

**Comment by wc-duck** [comment]
Sure... :)

You can start of with saying what you think should be in the readme and what should be in a wiki.

**Comment by RandyGaul** [comment]
I did my best to provide some content for a new readme version: https://github.com/wc-duck/datalibrary/issues/114

If I had an easier time getting everything to build and stuff, I'd be happy to write some more docs assuming I liked the library after trying it.

**Comment by RandyGaul** [comment]
Screw wiki. Put everything into readme file. Then if readme gets long it can be broken into multiple .md files and linked to directly within github master branch.

Wiki isn't good on github because it doesn't support pull requests. md files sitting in the repo are better for pull requests.

**Comment by wc-duck** [comment]
Closed as sup of #114
