### ISSUE TITLE
doc: document dl-json

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#121]
DL uses json... isch ;)
Document the difference.

* Valid json IS valid dl-json
* DL-json support comments // and /**/
* DL json can use '' or "" for strings/keys
* in dl-json '' or "" is optional on keys
* Keys need to be valid c-identifiers
* , is accepted for last item in array and map
* new-line in strings are valid, or
'my_str' : "whoo
Whaaa
Whiiii"

**Comment by RandyGaul** [comment]
What is map?

**Comment by wc-duck** [comment]
A {} in json
