### ISSUE TITLE
add support for binary format for all int-types

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#126]
All int-types (int8-64, uint8-64, bitfields and enums) should parse from binary int this form b100101.
This would mostly be useful when defining enums.

**Comment by wc-duck** [comment]
@lundmark would this be useful for you?

**Comment by lundmark** [comment]
This would be very helpful, not quite as helpful as the bitshift functionality, but almost!

**Comment by wc-duck** [comment]
I can see that, just thought this was an easy first step.
