### ISSUE TITLE
Compare to ProtoBuf，what's the advantage of datalibrary?

### ISSUE THREAD

**Issue by lxliu** [wc-duck/datalibrary#130]
I just have a quick lookup of datalibrary,
My currtent view is that , it's function is just a small sub set of ProtoBuf

so I want to know, if it has some features, is better than ProtoBuf?

**Comment by wc-duck** [comment]
Honestly I do not have enough knowledge about protobuf and it's internals to be able to give you an honest answer and I really do not have the free time to investigate that much.
With that said the lib that inspired datalibrary was itself inspired by protobuf so I would assume that there are plenty of similarity between the libs.
Something I can however do for you is answer specific questions about datalibrary itself.
Any specific features that you miss from protobuf, if you tell me I'm pretty sure I can answer why it do not exist or if it is something I could consider for addition.

**Comment by wc-duck** [comment]
I'll close this issue for now, please reopen if you have any questions.
