### ISSUE TITLE
Max member size on struct is 64

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#133]
And this is implicit, not documented and not errored/warned anywhere.

This is used when packing an instance there's a bitfield that's 64 bits long that's used to mark members used/not used.

**Comment by wc-duck** [comment]
That limit can absolutely be increased and handled, but I wonder, is 64 enough? I guess not as you have reached the limit?

**Comment by wc-duck** [comment]
Added a check when building the typelib + upped the maximum amount of members to 2048, that should be enough for anyone ;)
