### ISSUE TITLE
Replace yajl with custom json parser.

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#15]
Why?

One dependency less ( the last one! )
Bit most of all I think that it would open up for lots of optimizations a general json parser can't do that dl could since we have the type info.

However first some benchmarks need to be written, code can never be called optimized without numbers :)

**Comment by lundmark** [comment]
How willing are you to move away from json to something that accepts json and more (such as simplified json?)

**Comment by wc-duck** [comment]
Depends... I see the point and have gotten the request before but I'm still not sure on throwing out standard compliance.
I guess that you would like some thing such as optional " and being OK with , at the end of arrays etc?

**Comment by wc-duck** [comment]
After some thinking I might accept some changes. As long as dl read ( and simplified ) and write standard json it should be OK. One might want to add some way to force standard json but optional.
What simplifications is it that you are thinking about?

**Comment by lundmark** [comment]
I was basically thinking of adapting the sjson (simple json) format, but I now realize that almost no one uses it... but yes pretty much what you were thinking of (OK with , at the end of arrays etc), and having keys without "'s as long as they don't contain any whitespaces. What's the scenario where the optimizations for json-parsing is needed?

**Comment by wc-duck** [comment]
There are no real reasons right now to optimize the text parse. However doing this will simplify the worst part of the codebase quite a bit I think ( dl_txt.cpp ).
Also getting rid of a dependency is always nice!

**Comment by wc-duck** [comment]
This task will also contain replacing the format of dl-text instances.
Right now the format is as follows:
{
    "type" : "name_of_type",
    "data" : {
        "member1" : 1,
        "member2" : 2,
        "a_pointer" : 1
    },
    "subdata" : {
        "#1" : { ... }
    }
}

and will be changed to:
{
    "name_of_type" : {
        "member1" : 1,
        "member2" : 2,
        "a_pointer" : 1,
        "__subdata" : {
            "#1" : { ... }
        }
    }
}

in this format all keys in struct starting with __ is reserved for dl and the outer {} are optional.

**Comment by wc-duck** [comment]
As a heads up, this has been started an is progressing nicely!

**Comment by lundmark** [comment]
That is awesome to hear!

**Comment by wc-duck** [comment]
First tests indicate that the rewrite has already payed off performance-wise, and I have not done ANY optimization yet.

old code:
void dlbench_txt_pack_small_array_fp32() - 1000 iterations in 6.193813 ms
  - avg 0.006194 ms
  - min 0.005963 ms
  - max 0.040753 ms
void dlbench_txt_pack_big_array_fp32() - 1000 iterations in 910.955627 ms
  - avg 0.910956 ms
  - min 0.902558 ms
  - max 1.202714 ms
void dlbench_txt_pack_big_array_fp32_zero() - 1000 iterations in 572.332214 ms
  - avg 0.572332 ms
  - min 0.562232 ms
  - max 1.052374 ms
void dlbench_txt_pack_big_array_array_fp32() - 1000 iterations in 1804.845337 ms
  - avg 1.804845 ms
  - min 1.793033 ms
  - max 2.262627 ms
void dlbench_txt_pack_big_array_str() - 1000 iterations in 473.479126 ms
  - avg 0.473479 ms
  - min 0.466268 ms
  - max 1.067398 ms
void dlbench_txt_pack_big_array_str_null() - 1000 iterations in 402.230713 ms
  - avg 0.402231 ms
  - min 0.400603 ms
  - max 0.471352 ms


new code:
void dlbench_txt_pack_small_array_fp32() - 1000 iterations in 1.268696 ms
  - avg 0.001269 ms
  - min 0.001211 ms
  - max 0.003712 ms
void dlbench_txt_pack_big_array_fp32() - 1000 iterations in 550.460388 ms
  - avg 0.550460 ms
  - min 0.546478 ms
  - max 0.751812 ms
void dlbench_txt_pack_big_array_fp32_zero() - 1000 iterations in 290.626648 ms
  - avg 0.290627 ms
  - min 0.288409 ms
  - max 0.471322 ms
void dlbench_txt_pack_big_array_array_fp32() - 1000 iterations in 1260.625244 ms
  - avg 1.260625 ms
  - min 1.252783 ms
  - max 1.747127 ms
void dlbench_txt_pack_big_array_str() - 1000 iterations in 405.798798 ms
  - avg 0.405799 ms
  - min 0.404093 ms
  - max 0.642168 ms
void dlbench_txt_pack_big_array_str_null() - 1000 iterations in 312.551117 ms
  - avg 0.312551 ms
  - min 0.311262 ms
  - max 0.487755 ms

**Comment by lundmark** [comment]
Heyyy nice :)

**Comment by lundmark** [comment]
Good job!

**Comment by wc-duck** [comment]
This has now been pushed in its own branch, feel free to test it out and report bugs/issues.

**Comment by lundmark** [comment]
Awesome! 

I will try to look into it this weekend. Great job!

**Comment by wc-duck** [comment]
Merged to main recently.
