### ISSUE TITLE
dl_tlc reacts poorly to arguments

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#16]
dl_tlc.exe -c test.h -o test.bin test.json

With the test json from the documentation fails to read test.h

dl_tlc.exe -c test.h test.json

Spews the generated header to stdout.

Expected behavior for case 1 would be that it creates the file if it doesn't exist, and also outputs the generated header there. Creating the file test.h yields only a test.bin generated.

Expected behavior for case 2 would be that it creates the file if it doesn't exists and overwrites any data inside it with the generated header.

**Comment by wc-duck** [comment]
Well that is really a poor resultat. A quick glance of the code confirms that the code now uses -o for output all the time and just use -c etc to determine "mode" and modes can't be combined in one run of dl_tlc.

I don't remember why I did it like this but for a short-term solution, just run dl_tlc twice with different options.

I'll look over the argument and at least add decent error-messages and doc.

**Comment by wc-duck** [comment]
The two runs would be

dl_tlc -o test.bin test.json
do_tlc -c -o test.h test.json

**Comment by lundmark** [comment]
This works! Thanks!

**Comment by wc-duck** [comment]
I have added a check that the flags is set correctly now.
