### ISSUE TITLE
Running dl_tlc.exe with a library consisting of an enum and an empty type crashes

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#17]
This test case crashes the dl_tlc when running it as:
dl_tlc.exe -c -o output.h input.json

```
{
	"module" : "component_resources",
	"enums" : {
		"damage_types" : {
			"DAMAGE_SLASHING" : 0,
			"DAMAGE_CRUSHING" : 1,
			"DAMAGE_PIERCING" : 2,
			"DAMAGE_HEAT" : 3,
			"DAMAGE_COLD" : 4,
			"DAMAGE_ELECTRIC" : 5,
			"DAMAGE_CORROSIVE" : 6,
			"DAMAGE_MENTAL" : 7,
			"DAMAGE_POISON" : 8,
			"DAMAGE_RADIATION" : 9,
			"DAMAGE_NUM_TYPES" : 10
		}
	},
	"types" : {
		"damage_component_resource" : {
			"members" : [
			]
		}
	}
}
```

**Comment by wc-duck** [comment]
Are you using the empty struct or was that just a typo that should have been an error? As far as I know an empty struct is invalid I c an 1 byte in c++ ( or is that compiler dependent? ).
I might add support for empty structs if you have a compelling usecase, otherwise it will only be an error. However it shouldn't be a crash :)

**Comment by lundmark** [comment]
Hmm, you're right. This doesn't work in a C-environment. Yeah then this should definitely be an error.

**Comment by wc-duck** [comment]
What was your usecase? Maybe there is some other thing we can do to help out?

**Comment by lundmark** [comment]
Well, basically my structure looks like this:
array[] : TYPE_ID's
array[] : component_resource-pointer

And I just basically wanted a TYPE-ID for something as a marker with no data bound to it.

I just need to add static hashes and invent one myself :) No worries.

**Comment by wc-duck** [comment]
I have had plans to add something like that for a while but I do not see it getting in soon. I'll push a fix for this now and close the issue.
