### ISSUE TITLE
dl_tlc should not open output file until input file has been parsed

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#21]
Otherwise it cleans / overwrites the output file even if the input file is corrupt / not possible to parse.

**Comment by lundmark** [comment]
... which can be particularly bitter if you're pilling on your buildsystem and happen to reverse the order of the files so you try to take the output files and use them as input files, and the input files as output files...

... specifically if you have no version control software because you're "too cool for school".

**Comment by wc-duck** [comment]
Agreed, I'll fix this when the son has his nap-time ;)

**Comment by wc-duck** [comment]
Should be fixed by the last commit.
