### ISSUE TITLE
Feature: enum-values as size on static arrays

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#22]
This would be very nice

```
{
	"module" : "my_module",
	"enums" : {
		"some_enum" : {
			"SOME_THING",
                        "SOME_THING2",
                        "NUM_THINGS"
		}
	},
	"types" : {
		"my_type" : {
			"members" : [ 
				{ "name" : "some_things", "type" : "some_enum[NUM_THINGS]" }
			]
		}
	}
}
```

So that if you go in and modify the enum, the result will still be good and not missing to increase the value on your static array.

**Comment by wc-duck** [comment]
I think that something like this would be a good thing but I would like to take my time to see if there are any other way to do this. Just to see all options. 
If you have any other ideas, please shout.
( my guess right now is that this will be the solution )

**Comment by lundmark** [comment]
I think that this is probably the way to do it - you probably don't even want to worry about looking it up in an enum. I mean the case could also be that the user wants to include a header-file of their own where they have an enum that they want to use. Or maybe that would break the library format?

**Comment by wc-duck** [comment]
I need the size in the compiled typelib so I will need to look up the enum but that shouldn't be hard.
I have thought about adding support for constants outside of enums l and that could be used here.
But I agree that this is a simple solution and a good thing to do.

**Comment by lundmark** [comment]
Constants outside of enums is only supported in C++, not C though... I think? If you think of static const mytype myvalue = 7; ? 

But yeah, I think that allowing enums as limiters for the size of an array would be fine but then only if it's defined in the same module  / headerfile. I guess it would be even nicer if you could set that your module/headerfile is dependent on another module for things like that so you can use enums/types from a different module.

**Comment by lundmark** [comment]
OMG <3
