### ISSUE TITLE
Enums as members does not compile in c

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#24]
```
{
	"module" : "stuff",
	"enums" : {
		"my_enum" : {
			"THIS_IS_ENUM" : 0
		}
	},
	"types" : {
		"my_thing" : {
			"members" : [ 
				{ "name" : "this_is_it", "type" : "my_enum" }
			]
		}
	}
}
```

generates a struct that looks like this:
```
struct my_thing
{
    my_enum this_is_it;
};
```

Which unfortunately does not compile in c. I assume that the same thing happens when you do the same thing with structs. I'd suggest either adding the "enum" / "struct" keyword to the types (preferably) or do the c-style of declaration with typedef enum my_enum {} my_enum;

**Comment by lundmark** [comment]
This will be solved by https://github.com/wc-duck/datalibrary/pull/25

**Comment by wc-duck** [comment]
I really need to get some c-compile tests going... I'll check your pr right away.

**Comment by wc-duck** [comment]
Merged.
