### ISSUE TITLE
Arrays of struct-pointers becomes static pointers.

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#26]
```
			"members" : [
				{ "name" : "mystuff", "type" : "previously_declared_struct_type*[10]" },
			]
```
generates the following code:

`const struct previously_declared_struct_type* mystuff;`

Is this really intended? I would assume that we would get this:

`struct previously_declared_struct_type* mystuff[10];`

**Comment by wc-duck** [comment]
This is not supported yet so I guess this is only a case of me not capturing this. It should be supported but I guess that it will fail during save/load.

**Comment by wc-duck** [comment]
Duplicate #28
