### ISSUE TITLE
Assigning a pointer in dl-txt to 0 does not work as expected

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#30]
There should be an error that DL doesn't find the pointer pointed to (since 0 is never used)

**Comment by wc-duck** [comment]
Item 0 is actually valid since it point to the root object ( so that you can point back to it ).
However there was no error checking for this exact case so this slipped by the type-check.

In the long run I think that I will rework how pointers are identified. I'll add a new issue for it.
