### ISSUE TITLE
Rework how pointer-data is represented in text-data.

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#31]
Currently pointers in text data is an integer:

0 - root-item
1 > items in the sub_data-section where each key is the matching number as a string. Such as

"subdata" : {
   "1" : { ... },
   "2" : { ... },
}

The bad thing here is the discrepancy between string and int depending on position in text-data and its hard to read.

My idea is to replace pointer-data as strings all over the board, so when setting a pointer-member it becomes:

{
    "my_ptr_member1" : "my_first_sub_ptr",
    "my_ptr_member2" : "my_second_sub_ptr",
    "my_ptr_member2" : "__root__"
}

and in subdata

"subdata" : {
   "my_first_sub_ptr" : { ... },
   "my_second_sub_ptr" : { ... }
}

One potential problem with this, but some thing I accept, is that the pointer-names will not be kept when unpacking, so when doing a dl_txt_unpack() the pointers will be named "ptr1", "ptr2" etc.

**Comment by wc-duck** [comment]
this is done in the customjson branch...
subdata will be stored in an item in the struct with the name "__subdata" and both pointer-references and their instances are now strings.
The root-object can be referenced with "__root"

example:

`{
    "my_type" {
        "my_ptr_member" : "my_sub_instance",
        "__subdata" : {
            "my_sub_instance" : {
                "my_ptr_member" : "__root"
            }
        }
    }
}`

**Comment by lundmark** [comment]
This is really interesting. Can the pointer be of a different type than the data pointed to?

Do you catch my drift? So can I have a:

void* my_ptr;

that is pointed to something that dl will then store as a separate datatype (that exists in the dl-library)?

**Comment by wc-duck** [comment]
Nope... the data is still typed according to the type of the member pointing to it. I am thinking about adding something like a multi-type that would be represented as something like:

struct
```
{
    dl_type_id_t type;
    union {
         supported_type1* type1;
         supported_type2* type2;
         supported_type3* type3;
         supported_type4* type4;
    };
} member;

But that has some issues like unnecessary padding in the member ( between type and pointer ) on 64-bit, no real indication in text-format what actual type you are setting so I think that I need to work abit more on that.
An opaque pointer could be added but then again it would require re-working how sub-data is represented in the text-fmt since as it is now there is no type-info in the __subdata section.
```

**Comment by wc-duck** [comment]
... but it is something that I might want as well so it is definitively something that I will think about.
