### ISSUE TITLE
Storing DL_TYPE_ATOM_INLINE_ARRAY with DL_TYPE_STORAGE_STRUCT's doesn't correct pointers

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#36]
So if you write an atom inline array of structs with members that have pointers (such as strings), the storage fails to redirect the pointers to offsets.

**Comment by lundmark** [comment]
This is fixed by pull request:
https://github.com/wc-duck/datalibrary/pull/37

**Comment by wc-duck** [comment]
Fixed by PR.
