### ISSUE TITLE
Investigate if going towards hjson is a good idea.

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#45]
https://hjson.org/

There has been some requests of "loosening" the json input to DL and I can absolutely understand why.

The only thing that I do not like about it is that by doing that DL will not be readable by "any conforming json parser" such as pythons json module etc. However that might not be a problem and it is worth more to have a simple format for humans.

The format would still be writable by any tool so that should be fine.

If there is anyone reading, feel free to comment :)

**Comment by joeldevahl** [comment]
I would be perfectly happy if the typelib and data text *reader* would accept hjson or some json superset. Writing on the other hand could still be json only so that exported data can be shared. The user can then take a conscious choice to write in a human simplified form.

**Comment by wc-duck** [comment]
Now that I have rewritten the parser for text-data it should be quite simple to add all the features that hjson supports.

I have thought about making it configurable to have "strict" parsing, but I think that will just make the code unnecessary complex for no real gain.

Now I only have to find time to do this ;)

Tasks that need to be done before this can be started:
* Port the typelib parser away from yajl.
* Get code coverage going.

**Comment by wc-duck** [comment]
Closing this and replacing it with issue #54
