### ISSUE TITLE
Typelibrary compiler fails if last line is not blank

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#49]
If you have your typelibrary definition that ends with a line that has the ending scope in it (a simple line with the last } on it) the typelibrary compiler fails with:

50>  expected '{' but got '@' at 114
50>  at line 0, col 0:
50>  @n�
50>   ^
50>  failed to load ty

This should either be checked and given a proper error rather than printing a bad buffer, OR it should be accepted.

**Comment by lundmark** [comment]
My bad, wrong error.

This is the correct error:

50>  failed to load typelib from "FILENAME HERE"
50>  expected string
50>  at line 2, col 0:
50>  }
50>   ^

**Comment by wc-duck** [comment]
I know this is late, but I do not seem to be able to reproduce this ( with latest code ), could you attach a repro-file?

**Comment by lundmark** [comment]
I can't reproduce this either.
