### ISSUE TITLE
Add extern feature to enums as well

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#61]
The extern feature for structs is awesome. It would be great to be able to have it on other features as well, such as enums.

**Comment by wc-duck** [comment]
That should not be a problem I guess!

**Comment by wc-duck** [comment]
Unittests says it works... feel free to test it out more!

**Comment by lundmark** [comment]
Perfect! Will look into merging this today!

On Wed, Jul 4, 2018 at 11:18 PM, Fredrik Kihlander <notifications@github.com
