### ISSUE TITLE
Issues with parsing type-strings

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#64]
If I define a struct member like this:
{ "name" : "apa", "type" : "Random *" },

and Random is a struct, the type outputted will not be a pointer but rather a normal struct (and no warning about it).

if I instead do
{ "name" : "apa", "type" : "Random*" },

it will become a:
const struct Random* apa;

I don't want it as const. Why is it const?

**Comment by wc-duck** [comment]
Both sound like bugs... I'll look into it!

**Comment by wc-duck** [comment]
I'll take a pass on bugs at lunch tomorrow!

**Comment by wc-duck** [comment]
This case ( and a whole bunch of other invalid formats/chars ) is detected now and reported as an error + giving suggestions on what is a valid format.
