### ISSUE TITLE
Add support for float as hex.

### ISSUE THREAD

**Issue by wc-duck** [wc-duck/datalibrary#68]
I'm thinking about adding support for parsing floats from hex-numbers as well as decimal that is supported now.

The reason being precision. If one would like to specify floats precisely today it might not be possible! (See disabled unit test)

It would work as follows.
If a float is parsed from hex it will just be read as an uint, or the bits of the float.
Text would also always be unpacked as hex + comment, maybe controlled by flag?

'my_float' : 0x12345678 /*0.2945*/

**Comment by lundmark** [comment]
I think this is a very good thing in general for the parser. This is really something that I want for enums.

**Comment by wc-duck** [comment]
This will most certainly be closed by #88

**Comment by wc-duck** [comment]
Fixed by fixing issue #88
