### ISSUE TITLE
Inline array of bitfield-types is silently ignored

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#76]
Having a member on a struct like this: 
				{ "name" : "this_is_not_what_I_expected", "type" : "bitfield:1[8]" }

Either the feature should be supported, or DL should fail/warn about unsupported type.

**Comment by wc-duck** [comment]
Yeah... That is clearly wrong. Will have to turn that into on error as I have no idea what an array of bitfields would actually mean.

**Comment by lundmark** [comment]
Yes, this should clearly be an error :)

On Fri, Feb 16, 2018 at 7:59 PM, Fredrik Kihlander <notifications@github.com
