### ISSUE TITLE
Support type limits for defaults

### ISSUE THREAD

**Issue by lundmark** [wc-duck/datalibrary#78]
I'd like to see the possibility to have for example:
{ "name" : "blah", "type" : "fp32", "default" : "-FLT_MAX" } functionality exposed so that we can set default values to min/max/epsilon etc for types.

**Comment by wc-duck** [comment]
I guess that could be done... We just need a better syntax than a string. Maybe just support min max in the same way as inf/nan ?

**Comment by lundmark** [comment]
That sounds like a great idea. min / max / epsilon ? also -max, -min,
-epsilon.

On Thu, May 17, 2018 at 2:35 PM, Fredrik Kihlander <notifications@github.com

**Comment by wc-duck** [comment]
Is this something you would still benefit from?

**Comment by wc-duck** [comment]
Should be fixed now, I however skipped 'epsilon' for float types, if you really need that feel free to add a new ticket!
